apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: node-api-platform
  path: ./gitops/apps/node-api/aws-nonprod
  prune: true
  dependsOn:
    - name: infrastructure
    - name: kyverno-policies
  wait: true
  timeout: 6m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars
