apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "node-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.app.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-api.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "node-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
