apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - enforce/resource-requirements.yaml
  - enforce/probes.yaml
  - enforce/pod-security-baseline.yaml
  - enforce/image-policy.yaml
  - audit/require-labels.yaml
  - audit/require-topology-spread.yaml
  - audit/require-pdb.yaml
  - audit/require-networkpolicy.yaml
  - audit/warn-broad-rbac.yaml
