apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: node-api-secret
  namespace: node-api-staging
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: node-api-aws
    kind: SecretStore
  target:
    name: node-api-secret
    creationPolicy: Owner
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: node-api/staging/api-token
