apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: node-api-aws
  namespace: node-api-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: node-api-secrets-reader
