apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: node-api-local
  namespace: node-api-production
spec:
  provider:
    kubernetes:
      remoteNamespace: node-api-production
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: node-api-production
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-local-reader
